app:
  name: ui
  image:
    repository: 'onecx/onecx-tenant-ui'
  routing:
    enabled: true
    path: /mfe/onecxTenant/

  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      spec:
        exposedModule: './OnecxTenantModule'
        description: 'OneCX OnecxTenant Module'
        note: 'OneCX OnecxTenant UI module auto import via MF operator'
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: 'onecx-tenant-ui'
# PIPE Config
